import type { Card } from '../types/card.ts';
import { buildPackCards, type CardSeed } from './cardBuilder.ts';

/**
 * 有料パック「動物」（100問以上）。哺乳類・鳥類・爬虫類・虫・海の生き物を幅広く収録する。
 * 各行は [日本語, English, カテゴリ(説明文の一般名詞・1語), 特徴句(3〜5語)]。
 * factにはカテゴリ語（animal/bird/fish等）自身をなるべく含めない
 * （"This animal is known for ... animal" のような不自然な反復を避けるため）。
 */
const ROWS: [string, string, string, string][] = [
  // 哺乳類 (30)
  ['ライオン', 'Lion', 'animal', 'a big cat with mane'],
  ['トラ', 'Tiger', 'animal', 'a big cat with stripes'],
  ['クマ', 'Bear', 'animal', 'a large furry forest dweller'],
  ['オオカミ', 'Wolf', 'animal', 'a wild dog that howls'],
  ['キツネ', 'Fox', 'animal', 'a sly reddish forest mammal'],
  ['ウサギ', 'Rabbit', 'animal', 'hopping around with long ears'],
  ['シカ', 'Deer', 'animal', 'a graceful mammal with antlers'],
  ['キリン', 'Giraffe', 'animal', 'the tallest long necked mammal'],
  ['シマウマ', 'Zebra', 'animal', 'a striped horse like mammal'],
  ['カバ', 'Hippopotamus', 'animal', 'a huge river loving mammal'],
  ['サイ', 'Rhinoceros', 'animal', 'a huge mammal with horn'],
  ['ラクダ', 'Camel', 'animal', 'a desert mammal with humps'],
  ['コアラ', 'Koala', 'animal', 'a sleepy leaf eating mammal'],
  ['パンダ', 'Panda', 'animal', 'a black white bamboo eater'],
  ['ゴリラ', 'Gorilla', 'animal', 'a huge strong forest primate'],
  ['チンパンジー', 'Chimpanzee', 'animal', 'a clever intelligent forest primate'],
  ['カメ', 'Turtle', 'reptile', 'a slow shelled crawling animal'],
  ['ヘビ', 'Snake', 'reptile', 'a long legless slithering animal'],
  ['トカゲ', 'Lizard', 'reptile', 'a small scaly quick creature'],
  ['カエル', 'Frog', 'creature', 'a small hopping pond creature'],
  ['フクロウ', 'Owl', 'bird', 'a quiet night hunting predator'],
  ['ワシ', 'Eagle', 'bird', 'a powerful raptor with talons'],
  ['オウム', 'Parrot', 'bird', 'a colorful chatterer copying sounds'],
  ['クジャク', 'Peacock', 'bird', 'bright fan shaped tail feathers'],
  ['フラミンゴ', 'Flamingo', 'bird', 'a pink wader balancing carefully'],
  ['ダチョウ', 'Ostrich', 'bird', 'a huge flightless running giant'],
  ['アヒル', 'Duck', 'bird', 'a water fowl that quacks'],
  ['ニワトリ', 'Chicken', 'bird', 'a farm fowl laying eggs'],
  ['ヒツジ', 'Sheep', 'animal', 'a woolly farm mammal bleating'],
  ['ヤギ', 'Goat', 'animal', 'a farm mammal climbing rocks'],

  // さらに哺乳類・鳥類など (30)
  ['ウマ', 'Horse', 'animal', 'a strong mammal people ride'],
  ['ウシ', 'Cow', 'animal', 'a farm mammal giving milk'],
  ['ブタ', 'Pig', 'animal', 'a pink farm mammal oinking'],
  ['アルパカ', 'Alpaca', 'animal', 'a fluffy wool bearing mammal'],
  ['ラマ', 'Llama', 'animal', 'a tall fluffy mountain mammal'],
  ['カワウソ', 'Otter', 'animal', 'a playful mammal swimming rivers'],
  ['ビーバー', 'Beaver', 'animal', 'a mammal building wooden dams'],
  ['リス', 'Squirrel', 'animal', 'a small mammal collecting nuts'],
  ['ハリネズミ', 'Hedgehog', 'animal', 'a small spiky curled mammal'],
  ['コウモリ', 'Bat', 'animal', 'a flying night hunting mammal'],
  ['アライグマ', 'Raccoon', 'animal', 'a masked mammal raiding trash'],
  ['スカンク', 'Skunk', 'animal', 'a smelly striped forest mammal'],
  ['モグラ', 'Mole', 'animal', 'a small mammal digging tunnels'],
  ['ネズミ', 'Mouse', 'animal', 'a tiny squeaking household mammal'],
  ['アリ', 'Ant', 'insect', 'a tiny hardworking colony worker'],
  ['ハチ', 'Bee', 'insect', 'a buzzing pollinator making honey'],
  ['テントウムシ', 'Ladybug', 'insect', 'a small red spotted beetle'],
  ['トンボ', 'Dragonfly', 'insect', 'a fast flying pond visitor'],
  ['バッタ', 'Grasshopper', 'insect', 'a critter jumping through grass'],
  ['コオロギ', 'Cricket', 'insect', 'a critter chirping at night'],
  ['ゴキブリ', 'Cockroach', 'insect', 'a fast scurrying unwanted pest'],
  ['サソリ', 'Scorpion', 'creature', 'a desert dweller with pincers'],
  ['カニ', 'Crab', 'creature', 'a sea dweller walking sideways'],
  ['エビ', 'Shrimp', 'creature', 'a small curled sea dweller'],
  ['タコ', 'Octopus', 'creature', 'a soft armed ocean dweller'],
  ['イカ', 'Squid', 'creature', 'a sea dweller squirting ink'],
  ['クラゲ', 'Jellyfish', 'creature', 'a soft see through stinger'],
  ['ヒトデ', 'Starfish', 'creature', 'a star shaped ocean dweller'],
  ['サメ', 'Shark', 'fish', 'a large predator with teeth'],
  ['クジラ', 'Whale', 'creature', 'the biggest animal living underwater'],

  // 海の生き物・爬虫類など (20)
  ['アザラシ', 'Seal', 'creature', 'a sleek flippered coastal swimmer'],
  ['セイウチ', 'Walrus', 'creature', 'a huge tusked arctic dweller'],
  ['カメレオン', 'Chameleon', 'reptile', 'a lizard changing its color'],
  ['イグアナ', 'Iguana', 'reptile', 'a large spiky tropical lizard'],
  ['ヤモリ', 'Gecko', 'reptile', 'a small lizard climbing walls'],
  ['コモドドラゴン', 'Komodo Dragon', 'reptile', 'a giant venomous island lizard'],
  ['カモノハシ', 'Platypus', 'creature', 'an odd furry egg layer'],
  ['ウォンバット', 'Wombat', 'animal', 'a stout burrowing Australian mammal'],
  ['ナマケモノ', 'Sloth', 'animal', 'an extremely slow tree mammal'],
  ['アルマジロ', 'Armadillo', 'animal', 'a mammal covered in armor'],
  ['ハイエナ', 'Hyena', 'animal', 'a scavenging mammal that cackles'],
  ['ミーアキャット', 'Meerkat', 'animal', 'a small alert desert mammal'],
  ['マングース', 'Mongoose', 'animal', 'a small mammal fighting snakes'],
  ['アナグマ', 'Badger', 'animal', 'a striped mammal digging burrows'],
  ['イタチ', 'Weasel', 'animal', 'a slender fast hunting mammal'],
  ['フェレット', 'Ferret', 'pet', 'a slender playful domesticated animal'],
  ['チンチラ', 'Chinchilla', 'pet', 'a soft fluffy plush rodent'],
  ['モルモット', 'Guinea Pig', 'pet', 'a small round furry rodent'],
  ['ハムスター', 'Hamster', 'pet', 'a tiny rodent storing food'],
  ['インコ', 'Parakeet', 'bird', 'a small colorful chatty pet'],

  // 鳥・魚・その他生き物 (20)
  ['ハクチョウ', 'Swan', 'bird', 'a graceful white lake dweller'],
  ['ガチョウ', 'Goose', 'bird', 'a large loud honking fowl'],
  ['コンドル', 'Condor', 'bird', 'a huge raptor soaring high'],
  ['ハヤブサ', 'Falcon', 'bird', 'the fastest diving hunting raptor'],
  ['カラス', 'Crow', 'bird', 'a clever black cawing scavenger'],
  ['スズメ', 'Sparrow', 'bird', 'a tiny common backyard visitor'],
  ['ハト', 'Pigeon', 'bird', 'a common city dwelling flyer'],
  ['ペリカン', 'Pelican', 'bird', 'a fishing hunter with pouch'],
  ['サンショウウオ', 'Salamander', 'creature', 'a small moist skinned amphibian'],
  ['ウミガメ', 'Sea Turtle', 'reptile', 'a shelled swimmer crossing oceans'],
  ['マンボウ', 'Sunfish', 'fish', 'a huge flat drifting swimmer'],
  ['マグロ', 'Tuna', 'fish', 'a large fast ocean swimmer'],
  ['サケ', 'Salmon', 'fish', 'a pink swimmer heading upstream'],
  ['ウナギ', 'Eel', 'fish', 'a long slippery slithering swimmer'],
  ['カジキ', 'Swordfish', 'fish', 'a spike nosed ocean swimmer'],
  ['カタツムリ', 'Snail', 'creature', 'a slow shelled crawling creature'],
  ['ナメクジ', 'Slug', 'creature', 'a slow slimy soft blob'],
  ['ミミズ', 'Earthworm', 'creature', 'a long creature living underground'],
  ['ガ', 'Moth', 'insect', 'a dusty winged nighttime flyer'],
  ['ホタル', 'Firefly', 'insect', 'a critter that glows softly'],
];

const seeds: CardSeed[] = ROWS.map(([ja, en, category, fact]) => ({ ja, en, category, fact }));

export const animalCards: Card[] = buildPackCards(seeds);
