import type { Card } from '../types/card.ts';
import { buildPackCards, type CardSeed } from './cardBuilder.ts';

/**
 * 有料パック「ビジネス」（100問以上）。役職・書類・イベント・ツール・スキル・お金の用語を収録する。
 * 各行は [日本語, English, カテゴリ(説明文の一般名詞・1語), 特徴句(3〜5語)]。
 */
const ROWS: [string, string, string, string][] = [
  // 役職・役割 (25)
  ['社長', 'CEO', 'role', 'the top leader of firms'],
  ['秘書', 'Secretary', 'role', 'an assistant who manages schedules'],
  ['会計士', 'Accountant', 'role', 'a person managing company numbers'],
  ['弁護士', 'Lawyer', 'role', 'a person arguing legal cases'],
  ['営業担当', 'Salesperson', 'role', 'someone convincing people to buy'],
  ['起業家', 'Entrepreneur', 'role', 'someone starting a new venture'],
  ['投資家', 'Investor', 'role', 'someone funding new growing companies'],
  ['人事担当', 'HR Staff', 'role', 'someone who hires new employees'],
  ['マーケター', 'Marketer', 'role', 'someone who promotes products cleverly'],
  ['コンサルタント', 'Consultant', 'role', 'an expert giving outside advice'],
  ['インターン', 'Intern', 'role', 'a trainee learning workplace skills'],
  ['フリーランス', 'Freelancer', 'role', 'someone working without one boss'],
  ['受付係', 'Receptionist', 'role', 'the first person visitors meet'],
  ['通訳者', 'Interpreter', 'role', 'someone translating words in meetings'],
  ['広報担当', 'PR Officer', 'role', "someone shaping a company's image"],
  ['エンジニア', 'Engineer', 'role', 'someone who builds technical systems'],
  ['デザイナー', 'Designer', 'role', 'someone who creates visual concepts'],
  ['マネージャー', 'Manager', 'role', 'someone leading a small team'],
  ['部下', 'Subordinate', 'role', 'a worker reporting to someone'],
  ['上司', 'Boss', 'role', 'the person you report to'],
  ['取引先', 'Business Partner', 'role', 'another company you work with'],
  ['面接官', 'Interviewer', 'role', 'someone asking questions before hiring'],
  ['新入社員', 'New Employee', 'role', 'someone who just joined recently'],
  ['同僚', 'Colleague', 'role', 'a person working beside you'],
  ['株主', 'Shareholder', 'role', 'someone owning part of firms'],

  // 書類・お金の用語 (25)
  ['契約書', 'Contract', 'document', 'a signed paper with terms'],
  ['名刺', 'Business Card', 'item', 'a small card with details'],
  ['履歴書', 'Resume', 'document', 'a summary of past jobs'],
  ['予算', 'Budget', 'term', 'a plan for spending money'],
  ['請求書', 'Invoice', 'document', 'a paper asking for payment'],
  ['領収書', 'Receipt', 'document', 'proof that you paid money'],
  ['会議', 'Meeting', 'event', 'people gathering to discuss plans'],
  ['プレゼン', 'Presentation', 'event', 'a talk explaining slides aloud'],
  ['出張', 'Business Trip', 'event', 'traveling somewhere for company work'],
  ['昇進', 'Promotion', 'event', 'getting a higher job title'],
  ['解雇', 'Layoff', 'event', 'losing your job unexpectedly'],
  ['退職', 'Retirement', 'event', 'leaving work for good eventually'],
  ['有給休暇', 'Paid Leave', 'term', 'time off with continued pay'],
  ['残業', 'Overtime', 'term', 'working extra hours past schedule'],
  ['在宅勤務', 'Remote Work', 'term', 'working from home not office'],
  ['目標設定', 'Goal Setting', 'term', 'deciding what to achieve next'],
  ['締め切り', 'Deadline', 'term', 'the day something must finish'],
  ['交渉', 'Negotiation', 'event', 'talking to reach a deal'],
  ['提携', 'Partnership', 'term', 'two companies working closely together'],
  ['合併', 'Merger', 'term', 'two companies joining into one'],
  ['買収', 'Acquisition', 'term', 'one company buying another completely'],
  ['倒産', 'Bankruptcy', 'term', 'a company unable to pay'],
  ['株式', 'Stock', 'term', 'a tiny share of ownership'],
  ['配当金', 'Dividend', 'term', 'profit shared with company owners'],
  ['損益計算書', 'Income Statement', 'document', 'numbers showing profit and loss'],

  // ツール・スキル (25)
  ['パソコン', 'Computer', 'tool', 'a machine used for typing'],
  ['プロジェクター', 'Projector', 'tool', 'a device that shows slides'],
  ['ホワイトボード', 'Whiteboard', 'tool', 'a board for writing ideas'],
  ['カレンダー', 'Calendar', 'tool', 'something tracking days and dates'],
  ['ファイル', 'File', 'document', 'papers kept together in order'],
  ['スプレッドシート', 'Spreadsheet', 'tool', 'a grid for organizing numbers'],
  ['メール', 'Email', 'tool', 'a written message sent online'],
  ['電話会議', 'Conference Call', 'event', 'talking with many people remotely'],
  ['チームワーク', 'Teamwork', 'skill', 'working well together toward goals'],
  ['リーダーシップ', 'Leadership', 'skill', 'guiding others toward shared goals'],
  ['時間管理', 'Time Management', 'skill', 'using hours wisely and efficiently'],
  ['コミュニケーション', 'Communication', 'skill', 'sharing ideas clearly with others'],
  ['問題解決', 'Problem Solving', 'skill', 'finding smart answers to difficulties'],
  ['交渉力', 'Negotiation Skill', 'skill', 'reaching agreements that satisfy everyone'],
  ['適応力', 'Adaptability', 'skill', 'adjusting easily to new situations'],
  ['集中力', 'Concentration', 'skill', 'staying focused without getting distracted'],
  ['創造力', 'Creativity', 'skill', 'coming up with fresh ideas'],
  ['責任感', 'Responsibility', 'skill', 'taking ownership of your actions'],
  ['生産性', 'Productivity', 'term', 'finishing a lot of tasks'],
  ['効率', 'Efficiency', 'term', 'doing tasks with little waste'],
  ['出社', 'Commuting To Office', 'term', 'traveling to work every morning'],
  ['転職', 'Job Change', 'event', 'moving to work somewhere new'],
  ['副業', 'Side Job', 'term', 'extra work done after hours'],
  ['起業', 'Starting A Business', 'event', 'launching a brand new company'],
  ['資金調達', 'Fundraising', 'event', 'collecting money to grow further'],

  // お金・組織・イベント (25)
  ['経費', 'Expenses', 'term', 'money spent while doing business'],
  ['税金', 'Tax', 'term', 'money owed to the government'],
  ['利益', 'Profit', 'term', 'money left after covering costs'],
  ['損失', 'Loss', 'term', 'spending more than you earn'],
  ['融資', 'Loan', 'term', 'money borrowed that gets repaid'],
  ['保証人', 'Guarantor', 'role', "someone backing another person's debt"],
  ['顧客', 'Customer', 'role', 'someone paying for goods sold'],
  ['供給業者', 'Supplier', 'role', 'a company providing needed materials'],
  ['競合他社', 'Competitor', 'role', 'another company selling similar things'],
  ['市場調査', 'Market Research', 'term', 'studying what customers really want'],
  ['ブランド', 'Brand', 'term', 'the identity customers recognize instantly'],
  ['広告', 'Advertisement', 'term', 'a message that tries selling'],
  ['顧客満足度', 'Customer Satisfaction', 'term', 'how happy buyers feel afterward'],
  ['労働組合', 'Labor Union', 'term', 'workers grouped to defend rights'],
  ['就業規則', 'Company Rules', 'term', 'official guidelines everyone must follow'],
  ['面接', 'Job Interview', 'event', 'a talk to evaluate someone'],
  ['内定', 'Job Offer', 'event', 'being picked for a role'],
  ['研修', 'Training Session', 'event', 'learning skills needed at work'],
  ['評価面談', 'Performance Review', 'event', 'a chat about your results'],
  ['社内報', 'Company Newsletter', 'document', 'updates shared among all staff'],
  ['組織図', 'Org Chart', 'document', 'a diagram showing reporting lines'],
  ['業務委託', 'Outsourcing', 'term', 'paying others to do tasks'],
  ['定例会議', 'Regular Meeting', 'event', 'a gathering held on schedule'],
  ['議事録', 'Meeting Minutes', 'document', 'notes of what was decided'],
  ['就業時間', 'Working Hours', 'term', 'the hours you must work'],
];

const seeds: CardSeed[] = ROWS.map(([ja, en, category, fact]) => ({ ja, en, category, fact }));

export const businessCards: Card[] = buildPackCards(seeds);
