import type { Card } from '../types/card.ts';
import { buildPackCards, type CardSeed } from './cardBuilder.ts';

/**
 * 有料パック「食べ物」（100問以上）。料理・デザート・果物・野菜・飲み物を幅広く収録する。
 * 各行は [日本語, English, カテゴリ(説明文の一般名詞・1語), 特徴句(3〜5語)]。
 */
const ROWS: [string, string, string, string][] = [
  // 料理 (30)
  ['ラーメン', 'Ramen', 'dish', 'noodles in a steaming broth'],
  ['カレー', 'Curry', 'dish', 'a spiced sauce over rice'],
  ['タコス', 'Taco', 'dish', 'a crunchy shell holding fillings'],
  ['ブリトー', 'Burrito', 'dish', 'a rolled wrap of fillings'],
  ['サンドイッチ', 'Sandwich', 'dish', 'fillings between two bread slices'],
  ['ハンバーガー', 'Hamburger', 'dish', 'a grilled patty in bread'],
  ['ホットドッグ', 'Hot Dog', 'dish', 'a grilled sausage in bread'],
  ['スパゲッティ', 'Spaghetti', 'dish', 'long thin noodles twirled around'],
  ['ラザニア', 'Lasagna', 'dish', 'layered pasta baked with cheese'],
  ['餃子', 'Dumpling', 'dish', 'small dough pockets holding fillings'],
  ['点心', 'Dim Sum', 'dish', 'small bite sized steamed snacks'],
  ['刺身', 'Sashimi', 'dish', 'thin slices of raw fish'],
  ['天ぷら', 'Tempura', 'dish', 'food lightly fried in batter'],
  ['うどん', 'Udon', 'dish', 'thick chewy wheat flour noodles'],
  ['そば', 'Soba', 'dish', 'thin noodles made from buckwheat'],
  ['味噌汁', 'Miso Soup', 'dish', 'a warm salty fermented broth'],
  ['フォー', 'Pho', 'dish', 'a fragrant herby noodle broth'],
  ['パッタイ', 'Pad Thai', 'dish', 'stir fried noodles with peanuts'],
  ['チャーハン', 'Fried Rice', 'dish', 'rice stir cooked with vegetables'],
  ['フライドチキン', 'Fried Chicken', 'dish', 'crispy battered pieces of poultry'],
  ['ステーキ', 'Steak', 'dish', 'a thick grilled beef cut'],
  ['ベーコン', 'Bacon', 'snack', 'thin salty strips of pork'],
  ['ソーセージ', 'Sausage', 'dish', 'ground meat stuffed in casing'],
  ['チーズ', 'Cheese', 'food', 'made from thick milk curds'],
  ['バター', 'Butter', 'food', 'a spread churned from cream'],
  ['ヨーグルト', 'Yogurt', 'food', 'a tangy creamy fermented item'],
  ['アイスクリーム', 'Ice Cream', 'dessert', 'a frozen sweet creamy treat'],
  ['チョコレート', 'Chocolate', 'dessert', 'a sweet treat from cacao'],
  ['キャンディ', 'Candy', 'dessert', 'a tiny colorful sugary treat'],
  ['クッキー', 'Cookie', 'dessert', 'a small sweet baked treat'],

  // デザート・スナック (25)
  ['ケーキ', 'Cake', 'dessert', 'a sweet baked celebration treat'],
  ['パイ', 'Pie', 'dessert', 'a crust holding sweet filling'],
  ['ドーナツ', 'Donut', 'dessert', 'a fried ring shaped snack'],
  ['パンケーキ', 'Pancake', 'dessert', 'a flat treat with syrup'],
  ['ワッフル', 'Waffle', 'dessert', 'a gridded treat with syrup'],
  ['クロワッサン', 'Croissant', 'dessert', 'a flaky buttery curved pastry'],
  ['ベーグル', 'Bagel', 'food', 'a dense ring shaped bread'],
  ['プレッツェル', 'Pretzel', 'snack', 'a twisted salty baked treat'],
  ['ポップコーン', 'Popcorn', 'snack', 'kernels that puff up hot'],
  ['ポテトチップス', 'Potato Chips', 'snack', 'thin fried crispy salty slices'],
  ['フライドポテト', 'French Fries', 'snack', 'long fried strips served hot'],
  ['サラダ', 'Salad', 'dish', 'a cold mix of greens'],
  ['スープ', 'Soup', 'dish', 'a warm savory liquid meal'],
  ['オムレツ', 'Omelette', 'dish', 'beaten eggs folded while cooking'],
  ['パスタ', 'Pasta', 'dish', 'wheat noodles served with sauce'],
  ['リゾット', 'Risotto', 'dish', 'creamy rice stirred slowly cooking'],
  ['パエリア', 'Paella', 'dish', 'a saffron rice meal cooked'],
  ['ケバブ', 'Kebab', 'dish', 'grilled meat served on skewers'],
  ['ファラフェル', 'Falafel', 'dish', 'fried balls made from chickpeas'],
  ['フムス', 'Hummus', 'dish', 'a smooth chickpea based dip'],
  ['ワカモレ', 'Guacamole', 'dish', 'a creamy green avocado dip'],
  ['サルサ', 'Salsa', 'dish', 'a chunky spicy tomato dip'],
  ['ケチャップ', 'Ketchup', 'spice', 'a sweet tangy tomato sauce'],
  ['マスタード', 'Mustard', 'spice', 'a sharp yellow tangy condiment'],
  ['マヨネーズ', 'Mayonnaise', 'spice', 'a creamy egg based sauce'],

  // 果物・その他食品 (25)
  ['ハチミツ', 'Honey', 'food', 'a sweet golden bee liquid'],
  ['ジャム', 'Jam', 'food', 'fruit cooked down into spread'],
  ['ピーナッツバター', 'Peanut Butter', 'food', 'a thick nutty creamy spread'],
  ['アボカド', 'Avocado', 'fruit', 'a creamy green tropical treat'],
  ['バナナ', 'Banana', 'fruit', 'a long yellow curved peel'],
  ['リンゴ', 'Apple', 'fruit', 'a crisp round juicy bite'],
  ['オレンジ', 'Orange', 'fruit', 'a round citrus juicy segment'],
  ['ブドウ', 'Grape', 'fruit', 'small round berries in bunches'],
  ['イチゴ', 'Strawberry', 'fruit', 'a small red dotted berry'],
  ['スイカ', 'Watermelon', 'fruit', 'a huge green watery giant'],
  ['パイナップル', 'Pineapple', 'fruit', 'a spiky crowned tropical treat'],
  ['マンゴー', 'Mango', 'fruit', 'a sweet juicy orange treasure'],
  ['ココナッツ', 'Coconut', 'fruit', 'a hard shelled tropical husk'],
  ['レモン', 'Lemon', 'fruit', 'a sour yellow citrus wedge'],
  ['ライム', 'Lime', 'fruit', 'a sour small green wedge'],
  ['サクランボ', 'Cherry', 'fruit', 'a tiny round red gem'],
  ['モモ', 'Peach', 'fruit', 'a soft fuzzy pink treat'],
  ['洋ナシ', 'Pear', 'fruit', 'a soft bell shaped treat'],
  ['キウイ', 'Kiwi', 'fruit', 'a fuzzy brown skinned gem'],
  ['ブルーベリー', 'Blueberry', 'fruit', 'a tiny dark purple orb'],
  ['トマト', 'Tomato', 'vegetable', 'a round red garden fruit'],
  ['ジャガイモ', 'Potato', 'vegetable', 'a starchy root grown underground'],
  ['ニンジン', 'Carrot', 'vegetable', 'a crunchy orange root crop'],
  ['タマネギ', 'Onion', 'vegetable', 'a layered bulb causing tears'],
  ['ニンニク', 'Garlic', 'vegetable', 'a small strong smelling bulb'],

  // 野菜・飲み物・主食 (20)
  ['ブロッコリー', 'Broccoli', 'vegetable', 'a green tree shaped crop'],
  ['ホウレンソウ', 'Spinach', 'vegetable', 'a dark leafy healthy green'],
  ['キノコ', 'Mushroom', 'vegetable', 'a fungus used in cooking'],
  ['トウモロコシ', 'Corn', 'vegetable', 'a yellow kernel covered crop'],
  ['カボチャ', 'Pumpkin', 'vegetable', 'a round orange autumn crop'],
  ['キュウリ', 'Cucumber', 'vegetable', 'a long cool crunchy green'],
  ['ピーマン', 'Bell Pepper', 'vegetable', 'a hollow colorful crunchy pod'],
  ['卵', 'Egg', 'food', 'an item laid by hens'],
  ['牛乳', 'Milk', 'drink', 'a white liquid from cows'],
  ['パン', 'Bread', 'food', 'a baked flour based staple'],
  ['お米', 'Rice', 'food', 'tiny white grains eaten worldwide'],
  ['麺', 'Noodles', 'food', 'long thin strands of dough'],
  ['コーヒー', 'Coffee', 'drink', 'a dark bitter morning brew'],
  ['紅茶', 'Tea', 'drink', 'a hot brew from leaves'],
  ['ジュース', 'Juice', 'drink', 'a sweet liquid from fruit'],
  ['炭酸飲料', 'Soda', 'drink', 'a fizzy sweet bubbly refreshment'],
  ['スムージー', 'Smoothie', 'drink', 'a thick blended fruit refreshment'],
  ['ミルクセーキ', 'Milkshake', 'drink', 'a thick cold blended treat'],
  ['豆腐', 'Tofu', 'food', 'a soft block from soybeans'],
  ['わさび', 'Wasabi', 'spice', 'a sharp green spicy paste'],
];

const seeds: CardSeed[] = ROWS.map(([ja, en, category, fact]) => ({ ja, en, category, fact }));

export const foodCards: Card[] = buildPackCards(seeds);
