import type { Card } from '../types/card.ts';
import { buildPackCards, type CardSeed } from './cardBuilder.ts';

/**
 * 有料パック「旅行」（100問以上）。国・ランドマーク・旅行用品・旅の行動を幅広く収録する。
 * 各行は [日本語, English, カテゴリ(説明文の一般名詞・1語), 特徴句(3〜5語)]。
 */
const ROWS: [string, string, string, string][] = [
  // 国 (30)
  ['フランス', 'France', 'country', 'a famous iron tower'],
  ['日本', 'Japan', 'country', 'cherry blossoms and shrines'],
  ['イタリア', 'Italy', 'country', 'pizza pasta and ruins'],
  ['スペイン', 'Spain', 'country', 'flamenco dancing and beaches'],
  ['ドイツ', 'Germany', 'country', 'castles beer and highways'],
  ['エジプト', 'Egypt', 'country', 'ancient pyramids and deserts'],
  ['ブラジル', 'Brazil', 'country', 'carnival dancing and rainforests'],
  ['オーストラリア', 'Australia', 'country', 'kangaroos and a red rock'],
  ['カナダ', 'Canada', 'country', 'maple syrup and mountains'],
  ['メキシコ', 'Mexico', 'country', 'tacos salsa and sombreros'],
  ['インド', 'India', 'country', 'colorful spices and palaces'],
  ['中国', 'China', 'country', 'a very long ancient wall'],
  ['タイ', 'Thailand', 'country', 'golden temples and islands'],
  ['ギリシャ', 'Greece', 'country', 'white houses by water'],
  ['スイス', 'Switzerland', 'country', 'snowy peaks and chocolate'],
  ['オランダ', 'Netherlands', 'country', 'windmills tulips and canals'],
  ['トルコ', 'Turkey', 'country', 'a bridge between continents'],
  ['ロシア', 'Russia', 'country', 'vast snowy plains and domes'],
  ['ペルー', 'Peru', 'country', 'an ancient city in mountains'],
  ['ケニア', 'Kenya', 'country', 'wide grasslands full of wildlife'],
  ['アイスランド', 'Iceland', 'country', 'glaciers volcanoes and bright lights'],
  ['ポルトガル', 'Portugal', 'country', 'colorful tiles and coastal towns'],
  ['モロッコ', 'Morocco', 'country', 'maze like markets and dunes'],
  ['ベトナム', 'Vietnam', 'country', 'floating markets and rice fields'],
  ['スウェーデン', 'Sweden', 'country', 'long winters and wooden cabins'],
  ['ノルウェー', 'Norway', 'country', 'deep fjords and midnight sun'],
  ['ニュージーランド', 'New Zealand', 'country', 'green hills and film sites'],
  ['韓国', 'South Korea', 'country', 'pop stars and spicy stews'],
  ['アルゼンチン', 'Argentina', 'country', 'tango dancing and grilled beef'],
  ['インドネシア', 'Indonesia', 'country', 'thousands of tropical volcanic islands'],

  // ランドマーク (25)
  ['エッフェル塔', 'Eiffel Tower', 'landmark', 'a tall iron Paris icon'],
  ['自由の女神', 'Statue of Liberty', 'landmark', 'a huge green harbor figure'],
  ['万里の長城', 'Great Wall of China', 'landmark', 'an ancient stone dragon path'],
  ['ギザのピラミッド', 'Pyramids of Giza', 'landmark', 'ancient stone triangles in Egypt'],
  ['コロッセオ', 'Colosseum', 'landmark', 'an ancient Roman fighting arena'],
  ['ビッグベン', 'Big Ben', 'landmark', 'a famous London clock tower'],
  ['マチュピチュ', 'Machu Picchu', 'landmark', 'ruins high in Peruvian mountains'],
  ['タージマハル', 'Taj Mahal', 'landmark', 'a white marble domed tomb'],
  ['サグラダファミリア', 'Sagrada Familia', 'landmark', 'an unfinished ornate church tower'],
  ['ゴールデンゲートブリッジ', 'Golden Gate Bridge', 'landmark', 'a red bridge in California'],
  ['ピサの斜塔', 'Leaning Tower of Pisa', 'landmark', 'a tilted historic bell tower'],
  ['ナイアガラの滝', 'Niagara Falls', 'landmark', 'powerful rushing water at border'],
  ['グランドキャニオン', 'Grand Canyon', 'landmark', 'a huge deep red gorge'],
  ['モンサンミッシェル', 'Mont Saint-Michel', 'landmark', 'an island abbey on tides'],
  ['ペトラ', 'Petra', 'landmark', 'an ancient city carved rock'],
  ['アンコールワット', 'Angkor Wat', 'landmark', 'a huge jungle temple complex'],
  ['ストーンヘンジ', 'Stonehenge', 'landmark', 'a mysterious circle of rocks'],
  ['シドニーオペラハウス', 'Sydney Opera House', 'landmark', 'a white sail shaped building'],
  ['クレムリン', 'Kremlin', 'landmark', 'a red walled government fortress'],
  ['バッキンガム宮殿', 'Buckingham Palace', 'landmark', 'a royal residence with guards'],
  ['ルーブル美術館', 'Louvre Museum', 'landmark', 'a huge glass pyramid entrance'],
  ['モアイ像', 'Moai Statues', 'landmark', 'giant stone heads on island'],
  ['兵馬俑', 'Terracotta Army', 'landmark', 'thousands of ancient clay soldiers'],
  ['ウルル', 'Uluru', 'landmark', 'a giant red rock formation'],
  ['ヴィクトリアの滝', 'Victoria Falls', 'landmark', 'a huge roaring water curtain'],

  // 旅行用品・語彙 (25)
  ['パスポート', 'Passport', 'item', 'a booklet needed to travel'],
  ['スーツケース', 'Suitcase', 'item', 'a case you pack clothes'],
  ['空港', 'Airport', 'place', 'a runway used for departures'],
  ['ホテル', 'Hotel', 'place', 'a room travelers rent overnight'],
  ['飛行機', 'Airplane', 'vehicle', 'a flying machine with wings'],
  ['電車', 'Train', 'vehicle', 'a long vehicle on rails'],
  ['タクシー', 'Taxi', 'vehicle', 'a car you hire briefly'],
  ['地図', 'Map', 'item', 'a drawing that shows directions'],
  ['観光客', 'Tourist', 'role', 'a visitor exploring new places'],
  ['ガイドブック', 'Guidebook', 'item', 'a book of travel tips'],
  ['両替', 'Currency Exchange', 'activity', 'swapping money for local cash'],
  ['お土産', 'Souvenir', 'item', 'a small gift from trips'],
  ['民宿', 'Guesthouse', 'place', 'a small cozy family inn'],
  ['国境', 'Border', 'place', 'the line between two countries'],
  ['時差ぼけ', 'Jet Lag', 'activity', 'feeling tired after long flights'],
  ['クルーズ船', 'Cruise Ship', 'vehicle', 'a huge boat for vacations'],
  ['キャンプ', 'Camping', 'activity', 'sleeping outdoors in a tent'],
  ['ハイキング', 'Hiking', 'activity', 'walking long trails in nature'],
  ['旅行かばん', 'Travel Bag', 'item', 'a bag for carrying gear'],
  ['予約', 'Reservation', 'activity', 'booking a seat in advance'],
  ['免税店', 'Duty Free Shop', 'place', 'a store with cheaper prices'],
  ['世界遺産', 'World Heritage Site', 'place', 'a protected spot of importance'],
  ['現地ガイド', 'Local Guide', 'role', 'a person showing tourists around'],
  ['乗り継ぎ', 'Layover', 'activity', 'waiting between two connecting flights'],
  ['展望台', 'Observation Deck', 'place', 'a high spot with views'],

  // 交通・旅の行動 (20)
  ['船', 'Ship', 'vehicle', 'a large vessel crossing oceans'],
  ['バス', 'Bus', 'vehicle', 'a long vehicle for riders'],
  ['自転車旅行', 'Bicycle Touring', 'activity', 'traveling slowly by pedal power'],
  ['島巡り', 'Island Hopping', 'activity', 'visiting many small islands quickly'],
  ['温泉旅行', 'Hot Spring Trip', 'activity', 'soaking in naturally heated water'],
  ['城巡り', 'Castle Visit', 'activity', 'exploring old fortified stone buildings'],
  ['街歩き', 'City Walking Tour', 'activity', 'strolling through streets on foot'],
  ['夜行バス', 'Overnight Bus', 'vehicle', 'traveling long distance while sleeping'],
  ['レンタカー', 'Rental Car', 'vehicle', 'a car you borrow temporarily'],
  ['国内旅行', 'Domestic Trip', 'activity', 'traveling without leaving your country'],
  ['海外旅行', 'Overseas Trip', 'activity', 'traveling far beyond your country'],
  ['一人旅', 'Solo Travel', 'activity', 'exploring new places all alone'],
  ['弾丸旅行', 'Whirlwind Trip', 'activity', 'seeing many sights very quickly'],
  ['蚤の市', 'Flea Market', 'place', 'a market of secondhand goods'],
  ['屋台', 'Food Stall', 'place', 'a small street snack cart'],
  ['地元料理', 'Local Cuisine', 'food', 'dishes unique to one region'],
  ['現地通貨', 'Local Currency', 'item', 'money used in one country'],
  ['入国審査', 'Immigration Check', 'activity', 'an officer checking your passport'],
  ['出国ゲート', 'Departure Gate', 'place', 'the point where flights begin'],
  ['時差', 'Time Difference', 'item', 'the gap between two clocks'],
];

const seeds: CardSeed[] = ROWS.map(([ja, en, category, fact]) => ({ ja, en, category, fact }));

export const travelCards: Card[] = buildPackCards(seeds);
